grammar RELS;

tokens {
	RELATIONSHIPS, RELATIONSHIP
}

relationships
	:	RELATIONSHIPS_START relationship+ RELATIONSHIPS_END
	;

relationship
	:	RELATIONSHIP_START id=ID_ATTR target=TARGET_ATTR rtype=TYPE_ATTR RELATIONSHIP_END
	;

RELATIONSHIP_START:	'RELATIONSHIP';
RELATIONSHIP_END:	'/RELATIONSHIP';
RELATIONSHIPS_START:	'RELATIONSHIPS';
RELATIONSHIPS_END:	'/RELATIONSHIPS';
ID_ATTR	:		'ID';
TARGET_ATTR:		'TARGET';
TYPE_ATTR:		'TYPE';	